In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

sns.set_theme()

In [2]:
# Load the penguins dataset
penguins = sns.load_dataset('penguins')
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [3]:
# a)
# Create the contingency table
contingency_table = pd.crosstab(penguins['species'], penguins['island'])
contingency_table

island     Biscoe  Dream  Torgersen
species                            
Adelie         44     56         52
Chinstrap       0     68          0
Gentoo        124      0          0

b)

$H_0$: The variables species and island are independent of each other.  
$H_A$: There is an association between the two variables species and island.

In [4]:
# b)
# Chi-squared test
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

print("Chi-squared statistic:", chi2)
print("P-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-squared statistic: 299.55032743148195
P-value: 1.3545738297192517e-63
Degrees of freedom: 4
Expected frequencies:
 [[74.23255814 54.79069767 22.97674419]
 [33.20930233 24.51162791 10.27906977]
 [60.55813953 44.69767442 18.74418605]]


The assumption regarding expected frequencies is met: The expected frequency in each cell is greater than 5.

$p < \alpha$. We reject the null hypothesis and claim with 95\% confidence that there is an association between species and island.  
The distributions of penguin species therefore differ between the islands.